### ISSUE TITLE
vnexpress.net is not a phishing website.

### ISSUE THREAD

**Issue by ngocnv83** [chainapsis/phishing-block-list#10]
VnExpress is a e-newspaper of Vietnam. It is not a phishing website.
Link website: https://vnexpress.net

**Comment by ctrl-Felix** [comment]
Fixed in #d693db1d396021bb1051a60b1bba3abfdbe5708f

Sorry for the delay, I really need to fix my notification settings

**Comment by ngocnv83** [comment]
Please recheck version [768c856](https://github.com/chainapsis/phishing-block-list/commit/768c856e4e250f8914cfec8952758f5ddf1e50c2). It's still add domain of e-newspaper vnexpress.net.
