### ISSUE TITLE
vnexpress.net is not a phishing website

### ISSUE THREAD

**Issue by ngocnv83** [chainapsis/phishing-block-list#11]
VnExpress is a e-newspaper of Vietnam. It is not a phishing website.
Link website: https://vnexpress.net/

After this domain was removed in https://github.com/chainapsis/phishing-block-list/commit/d693db1d396021bb1051a60b1bba3abfdbe5708f, it's still add in https://github.com/chainapsis/phishing-block-list/commit/768c856e4e250f8914cfec8952758f5ddf1e50c2

**Comment by ctrl-Felix** [comment]
I saw it. It seems like it hasn't been properly deleted in our backend. I will check it again tonight.

**Comment by ctrl-Felix** [comment]
Now it's properly deleted. Sorry for the inconvenience and thank you for reporting it.
