### ISSUE TITLE
phishing network

### ISSUE THREAD

**Issue by kanasite** [chainapsis/phishing-block-list#18]
coinchanger.nl - phishing exchange
ethereumixer.com - phishing mixer
bitmixing.xyz - phishing mixer
cryptomixer.ink - phishing mixer
btc-laundry.ink - phishing mixer
anonymixer.ink - phishing mixer
sec-qr-btc-eth.com - phishing qr code generator
qrforbtceth.net - phishing qr code generator

**Comment by ctrl-Felix** [comment]
Thank you very much

**Comment by kanasite** [comment]
@ctrl-Felix my github was compromised ( I just regained access ), I did not made these comments/issues
