### ISSUE TITLE
Report domains

### ISSUE THREAD

**Issue by FakesiteListHUN** [chainapsis/phishing-block-list#27]
Hello

I am also make a scam blocklist fraudulent online stores that primarily target Hungarian users, I thought you might add it to your own list.
[Raw link](https://raw.githubusercontent.com/FakesiteListHUN/FakeWebshopListHUN/refs/heads/main/fakewebshoplist)
[Repo link](https://github.com/FakesiteListHUN/FakeWebshopListHUN)

**Comment by ctrl-Felix** [comment]
Hi, thank you for bringing this up and maintaining such list!

Currently we are only adding domains from crypto-related scams so unfortunately we won't add your blocklist.
