### ISSUE TITLE
List of crypto scam domains

### ISSUE THREAD

**Issue by 0350d3a3a3ea40e3baa4aa6b34f71cfc** [chainapsis/phishing-block-list#28]
https://altdentifyer.xyz/discord/api/?key
https://connect.cloud-us-eu.com/connect.php
https://io.fixalgorithm.com/users/connect.html
https://webrectifier.com/access/1
https://mainnetdappshub.com/access/1

**Comment by 0350d3a3a3ea40e3baa4aa6b34f71cfc** [comment]
@kamal-sutra

**Comment by ctrl-Felix** [comment]
Thank you for submitting the domains. I added the ones that are still live
