### ISSUE TITLE
Add site - https://rolo-etherea.hunterdouglas.com.br/dappssystem/

### ISSUE THREAD

**Issue by 0350d3a3a3ea40e3baa4aa6b34f71cfc** [chainapsis/phishing-block-list#33]
https://rolo-etherea.hunterdouglas.com.br/dappssystem/

Malicious signing, attempts to steal funds

**Comment by ctrl-Felix** [comment]
Thank you, blocked in dfb79df7ef5b49e748ef46cb99ef5a6cf7deff23
