### ISSUE TITLE
[Block Domain] Boomchange.com Fraud - Fake Crypto Exchange Scam

### ISSUE THREAD

**Issue by Yandex41** [chainapsis/phishing-block-list#7]
Domain: www.boomchange.com

A fraudulent & fake Crypto Exchange which phishes people crypto coins. Formerly and now again it runs under their other domain boomchange.io too. Please add this to phishing detection system, thanks. More about the "Boomchange" fake exchange:
https://www.chainabuse.com/domain/boomchange.com
https://www.chainabuse.com/domain/boomchange.io

- [X] I have checked to make sure that [there is not a duplicate issue](https://github.com/chainapsis/phishing-block-list/issues)

**Comment by ctrl-Felix** [comment]
Added with commit 94bcda1

**Comment by Jerayer** [comment]
boomchange.com is a normal, working website that I use. They always send cryptocurrency on time...

**Comment by Yandex41** [comment]
Evidence proving the fraud of Boomchange can be found here:It looks like the scammer from Boomchange creates masses of fake and spam accounts to give his site a positive feedback, here is total, the evidence is clear that Boomchange is a scam and phishing.
Evidence proving the fraud of Boomchange can be found here: https://bitcointalk.org/index.php?topic=5454622.0
